### ISSUE TITLE
Do not require a curl container to send commands to Dynatrace

### ISSUE THREAD

**Issue by kristofre** [dynatrace-ace/dynatrace-jenkins-library#1]
At the moment, we need to use a container that has access to curl in order to communicate to Dynatrace:

```
stage('DT send deploy event') {
      steps {
        container("curl") {
          script {
            def status = pushDynatraceDeploymentEvent (
              tagRule : tagMatchRules,
              customProperties : [
                [key: 'Jenkins Build Number', value: "${env.BUILD_ID}"],
                [key: 'Git commit', value: "${env.GIT_COMMIT}"]
              ]
            )
          }
        }
      }
    }
```

This is because the function is using the curl command. 
This should be replaced with the [httpRequest Plugin](https://plugins.jenkins.io/http_request/) in order to make it easier to use and deploy in real-world pipelines.

**Comment by Andrewknackstedt** [comment]
Commit 19487165a0bff72c2f0ff91d51c3f9f740e04a92 addresses removes the need to use a curl command.

The enhancements have marked the old functions as deprecated, and will send a message when executed.
The new functions follow the correct naming scheme of dt_pushDynatrace[Type]Event.

**Comment by robertjahn** [comment]
I have tested a few of the new functions dt_pushXXX functions in a plain vanilla jenkins install (i.e. no custom containers) on MacOS, and they are working.
